import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
async function setup(page:Page){await page.addInitScript(()=>{class W{onmessage:((e:MessageEvent)=>void)|null=null;postMessage(m:{type:string;bitmap?:ImageBitmap}){if(m.type==='init')setTimeout(()=>this.onmessage?.(new MessageEvent('message',{data:{type:'ready'}})),0);m.bitmap?.close();}terminate(){}}Object.defineProperty(window,'Worker',{value:class extends W{constructor(){super();(window as any).__vision=this;}}});});await page.goto('/');await expect.poll(()=>page.evaluate(()=>Boolean((window as any).__vision?.onmessage))).toBe(true);}
async function feed(page:Page,mode='neutral'){await page.evaluate(mode=>{const palm=(x:number,y:number)=>{const p=Array.from({length:21},()=>({x,y}));p[0]={x,y:y+.12};for(let f=0;f<4;f++){const b=5+4*f,fx=x+(f-1)*.03;p[b]={x:fx,y};p[b+1]={x:fx,y:y-.04};p[b+2]={x:fx,y:y-.07};p[b+3]={x:fx,y:y-.1};}p[2]={x:x-.05,y:y+.07};p[3]={x:x-.07,y:y+.02};p[4]={x:x-.09,y:y-.03};return p;};const surprised=mode==='surprise'||mode==='raised';const face={mouth:{x:.5,y:.5},brow:{x:.5,y:.35},center:{x:.5,y:.4},top:.2,width:.25,jaw:surprised?.5:mode==='tinkov'?.3:0,smile:mode==='smile'?.8:0,scores:surprised?{browInnerUp:.7,eyeWideLeft:.5,eyeWideRight:.5}:{}};const h=palm(.67,.5);h[20]={x:.73,y:.54};(window as any).__vision.onmessage(new MessageEvent('message',{data:{type:'observation',observation:{time:performance.now(),aspect:4/3,face,hands:mode==='raised'?[palm(.1,.1),palm(.9,.1)]:mode==='tinkov'?[h]:[]}}}));},mode);}
async function hold(page:Page,mode='neutral',n=8){for(let i=0;i<n;i++){await feed(page,mode);await page.waitForTimeout(mode==='neutral'?160:100);}}
test('selected know meme migrates from chin to squint and fires with both eyes narrowed',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('memocam.preferences.v1'))localStorage.setItem('memocam.preferences.v1',JSON.stringify({assignments:{},enabled:['know'],exactPairs:['know:chin']}));});
 await setup(page);await hold(page,'neutral',9);await page.getByRole('button',{name:'Моя подборка',exact:true}).click();await expect(page.locator('.set-meme')).toHaveCount(1);await expect(page.getByRole('checkbox',{name:'Знаю, но не могу доказать: Смотри примерно прямо и прищурь оба глаза, не закрывая их полностью',exact:true})).toBeChecked();await page.getByRole('button',{name:'Тестировать выбранные'}).click();
 for(let i=0;i<8;i++){await page.evaluate(()=>{const face={mouth:{x:.5,y:.5},brow:{x:.5,y:.35},center:{x:.5,y:.4},top:.2,width:.25,jaw:0,smile:0,scores:{eyeSquintLeft:.3,eyeSquintRight:.25,eyeBlinkLeft:.1,eyeBlinkRight:.1}};(window as any).__vision.onmessage(new MessageEvent('message',{data:{type:'observation',observation:{time:performance.now(),face,hands:[]}}}));});await page.waitForTimeout(100);}
 await expect(page.getByRole('list',{name:'Журнал срабатываний'})).toContainText('Знаю, но не могу доказать');await expect(page.getByLabel('Условия: Прищур').locator('[data-pass=true]')).toHaveCount(5);await page.getByLabel('Условия: Прищур').scrollIntoViewIfNeeded();await page.screenshot({path:'docs/screenshots/squint-diagnostics.png'});await page.reload();await page.getByRole('button',{name:'Моя подборка',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(1);
});
test('chosen tab shows only current pairs and never replaces them with an older saved favorite',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('memocam.preferences.v1'))localStorage.setItem('memocam.preferences.v1',JSON.stringify({assignments:{},enabled:['okak','tinkov-ok'],exactPairs:['okak:surprise','tinkov-ok:skeptic'],favorite:{assignments:{},exactPairs:['tinkov-tongue:peek']}}));});
 await setup(page);await page.getByRole('button',{name:'Моя подборка',exact:true}).click();
 await expect(page.getByRole('tab',{name:'Моя подборка',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.locator('.set-meme')).toHaveCount(2);await expect(page.locator('.set-route-list input')).toHaveCount(2);await expect(page.locator('.set-list')).toContainText('Окак');await expect(page.locator('.set-list')).not.toContainText('Тиньков с папкой');
 await page.getByRole('button',{name:'Добавить из полного списка'}).click();await expect(page.locator('.set-meme')).toHaveCount(48);await page.getByRole('tab',{name:'Моя подборка',exact:true}).click();await expect(page.locator('.set-meme')).toHaveCount(2);
 await page.reload();await page.getByRole('button',{name:'Моя подборка',exact:true}).click();await expect(page.locator('.set-meme')).toHaveCount(2);
 await page.screenshot({path:'docs/screenshots/chosen-tab.png'});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/chosen-tab-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 await page.getByRole('checkbox',{name:/Окак:/}).click();await expect(page.locator('.set-meme')).toHaveCount(1);await page.getByRole('button',{name:'Снять все действия'}).click();await expect(page.locator('.set-meme')).toHaveCount(0);await expect(page.getByText('Здесь пока нет выбранных мемов. Добавь их из полного списка.')).toBeVisible();
});
test('exact two-meme set isolates actions, shows trial results and survives reload',async({page})=>{
 await setup(page);await hold(page,'neutral',9);await page.getByRole('button',{name:'Мой набор и тест',exact:true}).click();await expect(page.locator('.set-meme')).toHaveCount(48);await page.getByRole('button',{name:'Окак + Тиньков',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(2);await page.getByRole('button',{name:'Тестировать выбранные'}).click();
 await hold(page,'raised');await expect(page.getByRole('list',{name:'Журнал срабатываний'})).not.toContainText('Окак');await hold(page,'neutral',9);await hold(page,'tinkov');await expect(page.getByRole('list',{name:'Журнал срабатываний'})).toContainText('Тиньков с папкой');await expect(page.locator('.live-reaction')).toHaveCount(0);
 await hold(page,'neutral',9);await hold(page,'surprise');await expect(page.getByRole('list',{name:'Журнал срабатываний'})).toContainText('Окак');await page.screenshot({path:'docs/screenshots/exact-set-test.png'});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать полный список'}).click();expect((await download).suggestedFilename()).toBe('memocam-my-memes.md');
 await page.reload();await expect.poll(()=>page.evaluate(()=>Boolean((window as any).__vision?.onmessage))).toBe(true);await hold(page,'neutral',9);await hold(page,'smile');await expect(page.locator('.live-reaction')).toHaveCount(0);await hold(page,'neutral',9);await hold(page,'tinkov');await expect(page.locator('.live-reaction img')).toHaveAttribute('src','/media/tinkov-tongue.jpg');
});
test('route selection removes conflicting memes and an empty set stays empty on mobile',async({page})=>{
 await setup(page);await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Мой набор и тест',exact:true}).click();await page.getByRole('button',{name:'Снять все действия'}).click();await page.getByRole('checkbox',{name:'Узбагойся: Покажи открытую ладонь',exact:true}).check();await page.getByRole('checkbox',{name:'Сколько ты зарабатываешь?: Протяни одну ладонь',exact:true}).check();await expect(page.getByRole('checkbox',{name:'Узбагойся: Покажи открытую ладонь',exact:true})).not.toBeChecked();await expect(page.locator('.set-route-list input:checked')).toHaveCount(1);
 await page.getByRole('checkbox',{name:'Только выбранные',exact:true}).check();await expect(page.locator('.set-meme')).toHaveCount(1);await page.screenshot({path:'docs/screenshots/exact-set-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 await page.getByRole('button',{name:'Снять все действия'}).click();await page.reload();await page.getByRole('button',{name:'Мой набор и тест',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(0);
});
test('existing selection can be saved and restored explicitly without replacing current selection on reload',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('memocam.preferences.v1'))localStorage.setItem('memocam.preferences.v1',JSON.stringify({assignments:{},enabled:['okak','tinkov-ok'],exactPairs:['okak:surprise','tinkov-ok:skeptic']}));});
 await setup(page);await hold(page,'neutral',9);
 await page.getByRole('button',{name:'Мой набор и тест',exact:true}).click();await expect(page.locator('.meme-set .favorite-controls')).toContainText('2 действий');
 await page.getByRole('button',{name:'Снять все действия'}).click();await page.getByRole('button',{name:'Включить мою подборку',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(2);
 await page.getByRole('button',{name:'Тестировать выбранные'}).click();
 for(const mode of ['surprise','skeptic']){
  await hold(page,'neutral',9);
  for(let i=0;i<8;i++){
   await page.evaluate(mode=>{const face={mouth:{x:.5,y:.5},brow:{x:.5,y:.35},center:{x:.5,y:.4},top:.2,width:.25,jaw:mode==='surprise'?.25:0,smile:0,scores:mode==='surprise'?{browInnerUp:.17,eyeWideLeft:.02,eyeWideRight:.02}:{browOuterUpLeft:.19,browOuterUpRight:.06}};(window as any).__vision.onmessage(new MessageEvent('message',{data:{type:'observation',observation:{time:performance.now(),aspect:4/3,face,hands:[]}}}));},mode);await page.waitForTimeout(100);
  }
 }
 await expect(page.getByRole('list',{name:'Журнал срабатываний'})).toContainText('Окак');await expect(page.getByRole('list',{name:'Журнал срабатываний'})).toContainText('Сомнительно, но окей');
 await expect(page.getByLabel('Условия: Скепсис').locator('[data-pass=true]')).toHaveCount(4);
 await page.screenshot({path:'docs/screenshots/favorite-expressions.png'});
 await page.getByRole('button',{name:'Снять все действия'}).click();await page.reload();await page.getByRole('button',{name:'Мой набор и тест',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(0);await page.getByRole('button',{name:'Включить мою подборку',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(2);
 await page.getByRole('checkbox',{name:/Окак:/}).uncheck();await page.getByRole('button',{name:'Сохранить выбранные в мою подборку',exact:true}).click();await expect(page.locator('.meme-set .favorite-controls')).toContainText('1 действий');
 await page.reload();await page.getByRole('button',{name:'Мой набор и тест',exact:true}).click();await expect(page.locator('.set-route-list input:checked')).toHaveCount(1);await expect(page.getByRole('checkbox',{name:/Сомнительно, но окей: Приподними/})).toBeChecked();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'docs/screenshots/favorite-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
});
