import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
async function observations(page:Page){await page.addInitScript(()=>{
 class TestWorker {onmessage:((e:MessageEvent)=>void)|null=null;onerror=null;postMessage(m:{type:string;bitmap?:ImageBitmap}){if(m.type==='init')setTimeout(()=>this.onmessage?.(new MessageEvent('message',{data:{type:'ready'}})),0);m.bitmap?.close();}terminate(){}}
 Object.defineProperty(window,'Worker',{value:class extends TestWorker{constructor(){super();(window as any).__vision=this;}}});
 });}
async function feed(page:Page,pose=false){await page.evaluate((pose)=>{const face={mouth:{x:.5,y:.5},brow:{x:.5,y:.35},center:{x:.5,y:.4},top:.2,width:.25,jaw:pose?.3:0,smile:0};const x=.67,y=.5,p=Array.from({length:21},()=>({x,y}));p[0]={x,y:y+.12};for(let f=0;f<4;f++){const b=5+4*f,fx=x+(f-1)*.03;p[b]={x:fx,y};p[b+1]={x:fx,y:y-.04};p[b+2]={x:fx,y:y-.07};p[b+3]={x:fx,y:y-.1};}p[2]={x:x-.05,y:y+.07};p[3]={x:x-.07,y:y+.02};p[4]={x:x-.09,y:y-.03};(window as any).__vision.onmessage(new MessageEvent('message',{data:{type:'observation',observation:{time:performance.now(),face,hands:pose?[p]:[]}}}));},pose);}
test('default screen automatically runs actual camera models, hides catalogue and handles settings/pause/stop',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('.camera-message')).toHaveCount(0,{timeout:30000});await expect(page.locator('.live-feed')).toHaveJSProperty('readyState',4);await expect(page.locator('.live-reaction')).toHaveCount(0);await expect(page.locator('.meme-card')).toHaveCount(0);await page.keyboard.press('h');await expect(page.getByRole('dialog')).toBeVisible();await expect(page.locator('.live-meme-list>label')).toHaveCount(48);await page.locator('.advanced-camera>summary').click();await expect(page.getByRole('button',{name:'Моргенштерн · 4',exact:true})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);await page.keyboard.press('Space');await expect(page.getByText('Пауза · пробел — продолжить')).toBeVisible();await page.keyboard.press('h');await page.getByRole('button',{name:'Остановить камеру'}).click();await expect(page.locator('.live-feed')).toHaveJSProperty('srcObject',null);expect(errors).toEqual([]);});
test('observations trigger required folder image without a click, then release removes it',async({page})=>{await observations(page);await page.goto('/?pack=tinkov');await expect.poll(()=>page.evaluate(()=>Boolean((window as any).__vision?.onmessage))).toBe(true);for(let i=0;i<9;i++){await feed(page);await page.waitForTimeout(160);}await expect(page.locator('.calibration-note')).toHaveCount(0);await expect(page.locator('.live-reaction')).toHaveCount(0);for(let i=0;i<5;i++){await feed(page,true);await page.waitForTimeout(100);}await expect(page.locator('.live-reaction img')).toHaveAttribute('src','/media/tinkov-tongue.jpg');await expect(page.locator('.live-reaction')).toHaveClass(/right/);await page.keyboard.press('Escape');await page.screenshot({path:'docs/screenshots/realtime.png'});await feed(page);await expect(page.locator('.live-reaction')).toHaveCount(0,{timeout:2500});await page.keyboard.press('h');await page.locator('.advanced-camera>summary').click();await page.getByRole('button',{name:'Ни одного',exact:true}).click();await page.keyboard.press('Escape');for(let i=0;i<5;i++){await feed(page,true);await page.waitForTimeout(100);}await expect(page.locator('.live-reaction')).toHaveCount(0);});
test('actual face model calibrates a video fixture in the automatic scene',async({page})=>{await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{const im=new Image();im.src='/media/fish.jpg';await im.decode();const c=document.createElement('canvas');c.width=640;c.height=480;const ctx=c.getContext('2d')!;const draw=()=>ctx.drawImage(im,70,0,350,450,130,0,373,480);draw();setInterval(draw,65);return c.captureStream(15);};});await page.goto('/');await expect(page.locator('.camera-message')).toHaveCount(0,{timeout:30000});await expect(page.locator('.calibration-note')).toHaveCount(0,{timeout:15000});await expect(page.locator('.live-reaction')).toHaveCount(0);});
test('permission failure and narrow settings stay usable',async({page})=>{await page.setViewportSize({width:390,height:844});await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await page.goto('/');await expect(page.getByText(/Доступ к камере не разрешён/)).toBeVisible();await page.locator('.camera-message').getByRole('button',{name:'Жесты и настройки'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('textbox').fill('Шульман');await expect(page.locator('.live-meme-list>label')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.screenshot({path:'docs/screenshots/realtime-mobile-settings.png'});await page.getByRole('button',{name:'Закрыть настройки'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);});
test('real hand and face models trigger three source poses and clear on release',async({page})=>{
 await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const ctx=c.getContext('2d')!;let im=new Image();im.src='/media/fish.jpg';await im.decode();(window as any).__show=async(src:string)=>{const next=new Image();next.src=src;await next.decode();im=next;};const draw=()=>{ctx.fillStyle='#222';ctx.fillRect(0,0,640,480);if(im.src.endsWith('fish.jpg'))ctx.drawImage(im,70,0,350,450,130,0,373,480);else{const scale=Math.min(640/im.width,480/im.height);ctx.drawImage(im,(640-im.width*scale)/2,(480-im.height*scale)/2,im.width*scale,im.height*scale);}};draw();setInterval(draw,65);return c.captureStream(15);};});
 await page.goto('/?pack=all');await expect(page.locator('.camera-message')).toHaveCount(0,{timeout:30000});await expect(page.locator('.calibration-note')).toHaveCount(0,{timeout:15000});for(const src of ['/media/morgen-rock.png','/media/morgen-guns.jpg','/media/shulman-hands.jpg']){await page.evaluate(src=>(window as any).__show(src),src);await expect(page.locator('.live-reaction img')).toHaveAttribute('src',src,{timeout:12000});await page.keyboard.press('Escape');if(src.includes('guns'))await page.screenshot({path:'docs/screenshots/realtime-real-model.png'});await page.evaluate(()=>(window as any).__show('/media/fish.jpg'));await expect(page.locator('.live-reaction')).toHaveCount(0,{timeout:3500});}
});
test('a studio upload is used by automatic recognition in the clean scene',async({page})=>{await observations(page);await page.goto('/?studio=1&pack=tinkov');await page.getByRole('button',{name:'Подробнее о текущем меме'}).click();await page.getByLabel('Добавить свой медиафайл').setInputFiles('public/media/calm.jpeg');await expect(page.getByRole('button',{name:'Восстановить оригинал'})).toBeVisible();await page.goto('/?pack=tinkov');await expect.poll(()=>page.evaluate(()=>Boolean((window as any).__vision?.onmessage))).toBe(true);for(let i=0;i<9;i++){await feed(page);await page.waitForTimeout(160);}for(let i=0;i<5;i++){await feed(page,true);await page.waitForTimeout(100);}await expect(page.locator('.live-reaction img')).toHaveAttribute('src',/^blob:/);});
test('squirrel from the requested post triggers on wave and finishes its disappearance',async({page})=>{
 await observations(page);await page.goto('/?meme=squirrel-goodbye');await expect.poll(()=>page.evaluate(()=>Boolean((window as any).__vision?.onmessage))).toBe(true);for(let i=0;i<9;i++){await feed(page);await page.waitForTimeout(160);}
 for(const x of [.8,.85,.9,.95,1,.85,.8,.8,.8,.8]){await page.evaluate(x=>{const y=.4,p=Array.from({length:21},()=>({x,y}));p[0]={x,y:y+.12};for(let f=0;f<4;f++){const b=5+4*f,fx=x+(f-1)*.03;p[b]={x:fx,y};p[b+1]={x:fx,y:y-.04};p[b+2]={x:fx,y:y-.07};p[b+3]={x:fx,y:y-.1};}p[2]={x:x-.05,y:y+.07};p[3]={x:x-.07,y:y+.02};p[4]={x:x-.09,y:y-.03};(window as any).__vision.onmessage(new MessageEvent('message',{data:{type:'observation',observation:{time:performance.now(),face:{mouth:{x:.5,y:.5},brow:{x:.5,y:.35},center:{x:.5,y:.4},top:.2,width:.25,jaw:0,smile:0},hands:[p]}}}));},x);await page.waitForTimeout(100);}
 const clip=page.locator('.live-reaction video');await expect(clip).toHaveAttribute('src','/media/squirrel-goodbye.mp4');await feed(page);await expect.poll(()=>clip.evaluate((v:HTMLVideoElement)=>v.currentTime),{timeout:6500}).toBeGreaterThan(5.2);await page.screenshot({path:'docs/screenshots/squirrel-playing.png'});await expect(page.locator('.live-reaction')).toHaveCount(0,{timeout:3500});
});
test('broadcast runs with hidden-document flag and no RAF, without showing controls or points',async({page})=>{
 await page.addInitScript(()=>{Object.defineProperty(document,'hidden',{get:()=>true});window.requestAnimationFrame=()=>0;const W=Worker;Object.defineProperty(window,'Worker',{value:class extends W{constructor(...args:ConstructorParameters<typeof Worker>){super(...args);this.addEventListener('message',e=>{if(e.data.type==='observation')(window as any).__frames=((window as any).__frames??0)+1;});}}});});
 await page.goto('/?broadcast=1');await expect.poll(()=>page.evaluate(()=>(window as any).__frames??0),{timeout:30000}).toBeGreaterThan(5);await expect(page.locator('.camera-tools')).toBeHidden();await expect(page.locator('.landmark-overlay')).toBeHidden();await expect(page.locator('.live-feed')).toHaveCSS('transform','none');await page.keyboard.press('h');await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Остановить камеру'}).click();await expect(page.locator('.live-feed')).toHaveJSProperty('srcObject',null);
});
