import {legends} from './legends';
import { extraMemes } from './extraMemes';
export type PackId = 'classic' | 'fresh' | 'special' | 'tinkov';
export type GestureId = 'squint' | 'shockHands' | 'peekHello' | 'nod' | 'headNo' | 'skeptic' | 'smile' | 'surprise' | 'frown' | 'wink' | 'kiss' | 'disgust' | 'sad' | 'fingerGuns' | 'middle' | 'chinRest' | 'temple' | 'rock' | 'pinch' | 'steeple' | 'heart' | 'wave' | 'flex' | 'three' | 'shush' | 'chin' | 'peek' | 'handsUp' | 'palm' | 'paws' | 'wait' | 'swipe' | 'facepalm' | 'fish' | 'laugh' | 'hood' | 'point' | 'cheek' | 'glasses' | 'ears' | 'ok' | 'thumbs' | 'shrug' | 'victory';
export type Meme = {
  id: string; title: string; caption: string; gesture: GestureId;
  hint: string; detail: string; image: string; source: string;
  year: string; pack: PackId; emoji: string; accent: string;
  audio?: string; video?: string; targetOnly?: boolean; custom?: boolean; person?: string; minDisplayMs?:number;
};
export const packs: { id: PackId; label: string; description: string; emoji: string; person?: boolean; cover?: string }[] = [
  { id: 'classic', label: 'Золотая классика', description: 'Те самые, которые мы не забудем', emoji: '✦' },
  { id: 'fresh', label: 'Новая волна', description: 'Знакомые лица из ленты • 2025–2026', emoji: '↗' },
  { id:'tinkov', label:'Олег Тиньков', description:'Один Олег — восемь состояний души. Есть ненормативная лексика.', emoji:'😜',person:true,cover:'/media/tinkov-tongue.jpg' },
  { id: 'special', label: 'Иноагенты*', description: '8 персон: Тиньков, Дудь, Монеточка, Оксимирон, Моргенштерн, Шульман, Кац и Галкин', emoji: '◉' },
];
const source = (slug: string) => `https://memepedia.ru/${slug}/`;
export const memes: Meme[] = [
  { id:'tinkov-tongue', person:'tinkov', title:'Тиньков с папкой', caption:'Лицо серьёзного бизнеса.', gesture:'peek', hint:'Ладонь у щеки + открытый рот', detail:'Открой рот и поднеси одну раскрытую кисть сбоку к щеке, на уровне рта, словно прикрываешься папкой. Видны хотя бы три вытянутых пальца; вторую руку опусти. Можно высунуть язык для похожести, но язык и папка отдельно не определяются. Не закрывай рот и лицо полностью: модель должна видеть открытый рот. Удержи позу четверть секунды.', image:'/media/tinkov-tongue.jpg', source:'https://www.meme-arsenal.com/en/create/template/1524682', year:'Классика', pack:'tinkov', emoji:'😜', accent:'#e6e7cf' },
  { id:'tinkov-brave', person:'tinkov', title:'Это было смело', caption:'Очень. Очень смело.', gesture:'handsUp', hint:'Подними обе ладони', detail:'Подними две раскрытые кисти выше головы. В клипе есть ненормативная лексика.', image:'/media/tinkov-brave.jpg', video:'/media/tinkov-brave.mp4', source:'https://t.me/formemas/3702', year:'2022–2023', pack:'tinkov', emoji:'🙌', accent:'#dfebd0' },
  { id:'tinkov-mistake', person:'tinkov', title:'Я ошибся', caption:'Признаю. Бывает.', gesture:'wait', hint:'Соедини руки перед грудью', detail:'Сложи кисти вместе перед грудью, ниже подбородка, как будто просишь прощения. Обе кисти должны быть видны.', image:'/media/tinkov-mistake.jpg', video:'/media/tinkov-mistake.mp4', source:'https://t.me/formemas/3702', year:'2022–2023', pack:'tinkov', emoji:'🙏', accent:'#e6dfe9' },
  { id:'tinkov-uninterested', person:'tinkov', title:'Мне это неинтересно', caption:'Закроем вопрос.', gesture:'palm', hint:'Покажи ладонь «стоп»', detail:'Подними одну раскрытую ладонь сбоку от лица. Держи её на расстоянии примерно ширины лица, вторую руку опусти.', image:'/media/tinkov-uninterested.jpg', video:'/media/tinkov-uninterested.mp4', source:'https://t.me/formemas/3702', year:'2022–2023', pack:'tinkov', emoji:'✋', accent:'#dce6df' },
  { id:'tinkov-feel', person:'tinkov', title:'Я так чувствую', caption:'Аргумент, с которым не поспоришь.', gesture:'shrug', hint:'Разведи раскрытые ладони', detail:'Разведи две открытые кисти в стороны ниже подбородка, будто пожимаешь плечами. В клипе есть ненормативная лексика.', image:'/media/tinkov-feel.jpg', video:'/media/tinkov-feel.mp4', source:'https://t.me/formemas/3702', year:'2022–2023', pack:'tinkov', emoji:'🤷', accent:'#ece2d1' },
  { id:'tinkov-bike', person:'tinkov', title:'Катался на велике', caption:'Баланс работы и велосипеда.', gesture:'paws', hint:'Возьми воображаемый руль', detail:'Держи два кулака отдельно перед грудью, ниже подбородка, словно держишь руль. Это условный жест запуска, езду на велосипеде камера не проверяет.', image:'/media/tinkov-bike.jpg', video:'/media/tinkov-bike.mp4', source:'https://reactor.cc/post/3258323', year:'2017', pack:'tinkov', emoji:'🚲', accent:'#dce6e9' },

  ...legends,
  ...extraMemes,
  { id:'preved', title:'Превед, медвед!', caption:'Ну здравствуй, интернет.', gesture:'handsUp', hint:'Подними обе руки', detail:'Раскрой ладони и подними обе руки выше головы. Лицо и кисти должны полностью помещаться в кадре.', image:'/media/preved.gif', source:source('preved-medved'), year:'2006', pack:'classic', emoji:'🙌', accent:'#dceccf' },
  { id:'calm', title:'Узбагойся', caption:'Всё под контролем. Почти.', gesture:'palm', hint:'Покажи открытую ладонь', detail:'Одну открытую ладонь держи рядом с плечом, подальше от лица. Другую руку опусти.', image:'/media/calm.jpeg', source:source('uzbagoisya'), year:'2013', pack:'classic', emoji:'✋', accent:'#f0ddd5' },
  { id:'paws', title:'У меня лапки', caption:'Сегодня ничего не делаем.', gesture:'paws', hint:'Сложи кисти лапками', detail:'Подними две кисти под подбородок и согни пальцы как лапки. Держи кисти отдельно, близко к лицу.', image:'/media/paws.jpg', source:source('ne-mogu-u-menya-lapki'), year:'2017', pack:'classic', emoji:'🐾', accent:'#eedfcc' },
  { id:'wait', title:'Ждун', caption:'Когда ждёшь уже вечность.', gesture:'wait', hint:'Сложи руки и замри', detail:'Соедини кисти низко перед грудью и держи спокойно. Камера должна видеть обе кисти; руки под столом не подойдут.', image:'/media/wait.jpg', source:source('zhdun'), year:'2017', pack:'classic', emoji:'🤲', accent:'#e2e7e9' },
  { id:'magic', title:'Вжух!', caption:'И ты уже мем.', gesture:'swipe', hint:'Взмахни пальцем', detail:'Подними указательный палец и проведи им в сторону, как волшебной палочкой. Остальные пальцы согни, лицо не закрывай.', image:'/media/magic.png', source:source('vjuh'), year:'2016', pack:'classic', emoji:'🪄', accent:'#e8dff1' },
  { id:'fail', title:'Это фиаско, братан', caption:'Всё шло так хорошо…', gesture:'facepalm', hint:'Ладонь на лоб', detail:'Сначала посмотри в камеру, затем накрой лоб раскрытой ладонью. Не закрывай лицо полностью надолго.', image:'/media/fail.png', source:source('eto-fiasko-bratan'), year:'2017', pack:'classic', emoji:'🤦', accent:'#dbe5ee' },
  { id:'fish', title:'Я-аа-азь!', caption:'Вот она, рыба моей мечты!', gesture:'fish', hint:'Покажи большой улов', detail:'Разведи две руки по сторонам лица и открой рот. Руки держи ниже макушки, будто показываешь размер рыбы.', image:'/media/fish.jpg', audio:'/media/fish.mp3', source:source('jaaaaz'), year:'2011', pack:'classic', emoji:'🐟', accent:'#dce6cc' },
  { id:'cook', title:'Повар спрашивает повара', caption:'Когда сам придумал. Сам посмеялся.', gesture:'laugh', hint:'Улыбнись и открой рот', detail:'Улыбнись и открой рот. Руки опусти. В чистом режиме включён по умолчанию; в студии используй «Повтори мем».', image:'/media/cook.jpg', audio:'/media/cook.mp3', source:source('povar-sprashivaet-povara'), year:'2008', pack:'classic', emoji:'😂', accent:'#e1dfef', targetOnly:true },
  { id:'okak', title:'Окак', caption:'Вот это информация.', gesture:'surprise', hint:'Открой рот и приподними брови или раскрой глаза', detail:'Убери кисти из кадра. Открой рот и приподними брови либо раскрой глаза; сильное движение обоих признаков одновременно не требуется. Не улыбайся широко. Удержи выражение не менее половины секунды. В тесте индикаторы покажут, какое условие модель ещё не увидела. Поднятые руки не запускают этот мем.', image:'/media/okak.png', source:source('okak'), year:'2025', pack:'fresh', emoji:'😶', accent:'#e1e1e8' },
  { id:'decide', title:'Сам решу', caption:'У меня всё продумано.', gesture:'point', hint:'Указательный палец вверх', detail:'Покажи одной рукой указательный палец. Держи кисть в стороне от головы, остальные пальцы согни.', image:'/media/decide.jpg', source:source('sam-reshu'), year:'2025', pack:'fresh', emoji:'☝️', accent:'#edded0' },
  { id:'pupupu', title:'Пупупу…', caption:'Нужно немного подумать.', gesture:'cheek', hint:'Ладонь к щеке', detail:'Одну раскрытую кисть приложи к щеке, ниже уровня глаз. Немного наклони голову к ладони.', image:'/media/pupupu.png', source:source('pupupu'), year:'2025', pack:'fresh', emoji:'🤔', accent:'#f0dfeb' },
  { id:'glasses', title:'Умный человек в очках', caption:'Скачать обои. Бесплатно.', gesture:'glasses', hint:'Палец к переносице', detail:'Поднеси указательный палец к переносице, как будто поправляешь очки. Настоящие очки не нужны.', image:'/media/glasses.jpg', source:source('umnyj-chelovek-v-ochkax-skachat-oboi'), year:'2025', pack:'fresh', emoji:'🤓', accent:'#dbe6e4' },
  { id:'cheremsha', title:'Черемша', caption:'Тихо. Не спеша. Без суеты.', gesture:'ears', hint:'Покажи два ушка', detail:'Подними два указательных пальца над висками, как уши. Остальные пальцы на обеих руках согни.', image:'/media/cheremsha.jpg', source:source('cheremsha'), year:'2026', pack:'fresh', emoji:'🐰', accent:'#eadfcb' },
  { id:'tinkov-ok', person:'tinkov', video:'/media/tinkov-ok.mp4', title:'Сомнительно, но окей', caption:'Экспертная оценка получена.', gesture:'ok', hint:'Сделай жест OK', detail:'Соедини кончики большого и указательного пальцев в кольцо, остальные пальцы распрями. Держи руку подальше от лица.', image:'/media/tinkov-ok.jpg', source:'https://t.me/formemas/3702', year:'2023', pack:'special', emoji:'👌', accent:'#e1e9cc' },
  { id:'tinkov-wow', person:'tinkov', title:'Да это ж круто!', caption:'Олег одобряет.', gesture:'thumbs', hint:'Два больших пальца вверх', detail:'Покажи два больших пальца вверх, остальные пальцы согни. Обе кисти должны быть видны.', image:'/media/tinkov.jpg', source:source('tinkov-ocenivaet'), year:'2023', pack:'special', emoji:'👍', accent:'#f0e6c5' },
  { id:'dud', person:'dud', title:'Сколько ты зарабатываешь?', caption:'Тот самый вопрос.', gesture:'palm', hint:'Протяни одну ладонь', detail:'Протяни открытую ладонь в сторону камеры, немного ниже лица. Другую руку опусти.', image:'/media/dud.jpg', source:source('dud-i-shherbakov-pozhimayut-ruki'), year:'2017', pack:'special', emoji:'💸', accent:'#dfddec' },
  { id:'monetochka', person:'monetochka', title:'У тебя что ли два?', caption:'А сколько у тебя?', gesture:'victory', hint:'Покажи два пальца', detail:'Покажи V: указательный и средний пальцы распрямлены, остальные согнуты. Держи одну кисть в кадре.', image:'/media/monetochka.jpg', source:source('u-tebya-skolko-chto-li-dva'), year:'2023', pack:'special', emoji:'✌️', accent:'#efdbde' },
];

export type CustomMedia = { image?: string; video?: string; audio?: string; name: string };

export function inPack(meme:Meme,pack:PackId){return meme.pack===pack || meme.person===pack || (pack==='special'&&meme.person==='tinkov');}
