import type { Meme } from './catalog';
const p=(slug:string)=>`https://memepedia.ru/${slug}/`;
export const extraMemes:Meme[]=[
 {id:'squirrel-goodbye',title:'Белка — я исчезаю',caption:'Мои деньги после нового увлечения.',gesture:'wave',hint:'Помаши открытой ладонью туда-обратно',detail:'Подними одну раскрытую ладонь сбоку от лица и отчётливо помаши влево-вправо. Белка поднимает лапку и исчезает; клип доигрывает примерно 7 секунд после жеста. Это видео из присланного поста Threads, название карточки придумано для приложения. В общем наборе взмах чередует несколько мемов.',image:'/media/squirrel-goodbye.jpg',video:'/media/squirrel-goodbye.mp4',minDisplayMs:7000,source:'https://www.threads.com/@tennis_coaches_brothers/post/Dc5WkyxDWnN',year:'Пост проверен 05.09.2026',pack:'fresh',emoji:'🐿️',accent:'#dddeda'},
 {id:'oxxy-think',person:'oxxxymiron',title:'Оксимирон — синк эбаут ит',caption:'Think about it.',gesture:'temple',hint:'Указательный палец к виску',detail:'Повтори жест из кадра: один указательный палец сбоку у виска, остальные согнуты. Держи лицо открытым. Это исходная баттл-фраза Оксимирона; последующую пародию Гнойного не смешиваем с оригиналом.',image:'/media/oxxy-easy.png',source:p('izi-izi-ril-tok-sink-ebaut-it'),year:'2017',pack:'special',emoji:'🧠',accent:'#d6dde8'},
 {id:'morgen-guns',person:'morgenshtern',title:'Моргенштерн — та самая поза',caption:'Улыбка. Два пальца. Узнаваемо.',gesture:'fingerGuns',hint:'Пальцы «пистолетами» к вискам',detail:'Повтори позу с обложки: направь указательный и средний пальцы каждой руки к вискам, большие пальцы отставь. Безымянные и мизинцы согни. Рот и глаза оставь видимыми.',image:'/media/morgen-guns.jpg',source:'https://soundcloud.com/king-games-961909022/morgenshtern-mp3',year:'2020',pack:'special',emoji:'👉',accent:'#caddf0'},
 {id:'morgen-middle',person:'morgenshtern',title:'Моргенштерн — без комментариев',caption:'Ответ без слов.',gesture:'middle',hint:'Покажи один средний палец',detail:'Повтори жест из фотографии: средний палец распрямлён, остальные четыре согнуты. Одна кисть в кадре. Название — наша подпись к реальному фото, не цитата артиста.',image:'/media/morgen-middle.jpg',source:'https://click-or-die.ru/2020/11/morgenshtern/',year:'2020',pack:'special',emoji:'🖕',accent:'#ddd4df'},
 {id:'morgen-rock',person:'morgenshtern',title:'Моргенштерн — дикий',caption:'Рок-н-ролл на минималках.',gesture:'rock',hint:'Покажи «козу» одной рукой',detail:'Указательный палец и мизинец распрямлены, средний и безымянный согнуты. Такая форма кисти видна в исходном фото; это не утверждение об авторстве жеста «эщкере».',image:'/media/morgen-rock.png',source:'https://the-flow.ru/videos/morgenshtern-dikiy-plus-ep-hate-me',year:'2018',pack:'special',emoji:'🤘',accent:'#d7ddd2'},
 {id:'morgen-hello',person:'morgenshtern',title:'Моргенштерн — здорова!',caption:'Привет из раннего YouTube.',gesture:'wave',hint:'Помаши открытой ладонью туда-обратно',detail:'Одна раскрытая ладонь делает отчётливый взмах вправо-влево. Это жест запуска фирменного приветствия из ранних выпусков, а не уникальная поза из конкретного кадра. В оригинальном приветствии есть мат; исходный звук здесь не добавлен.',image:'/media/morgen-hello.png',source:p('morgenshtern'),year:'2017–2018',pack:'special',emoji:'👋',accent:'#d3dfe8'},
 {id:'shulman-hands',person:'shulman',title:'Шульман внимательно слушает',caption:'Сейчас разберёмся.',gesture:'chinRest',hint:'Сложи обе кисти под подбородком',detail:'Повтори положение рук на фото: соедини кисти и поднеси их под подбородок, не закрывая рот. Название и подпись придуманы для этой реакции; это не дословная цитата и не заявление об уникальном жесте Шульман.',image:'/media/shulman-hands.jpg',source:'https://www.rbc.ru/politics/08/06/2022/62a022be9a7947583fa44dfd',year:'2022',pack:'special',emoji:'🤔',accent:'#dedbd2'},
 {id:'katz-cat',person:'katz',title:'Кац и кот',caption:'Кот вошёл в план.',gesture:'paws',hint:'Две согнутые кисти у груди',detail:'Изобрази кота: две кисти лапками перед грудью. В исходном шаблоне Кац держит кота. Жест — наша адаптация, животное камера не распознаёт.',image:'/media/katz-cat.jpg',source:'https://www.meme-arsenal.com/create/template/11968460',year:'Шаблон',pack:'special',emoji:'🐈',accent:'#eadfd1'},
 {id:'galkin-max',person:'galkin',title:'Галкин Pro Max',caption:'Обновление установлено.',gesture:'flex',hint:'Два кулака по бокам головы — «бицепсы»',detail:'Подними два кулака по бокам головы, будто показываешь бицепсы. Это условный жест к мему Max → Pro Max про смену образа, а не точная поза исходного фото. Телосложение, бороду и привлекательность камера не оценивает.',image:'/media/galkin-max.jpg',source:'https://www.dailyshow.ru/news/maksim-galkin/29444/',year:'2026',pack:'special',emoji:'💪',accent:'#d5ded3'},
 {id:'dud-handshake',person:'dud',title:'Дудь и Щербаков — пятюня',caption:'Контакт установлен.',gesture:'wave',hint:'Протяни ладонь и махни вбок',detail:'Одна раскрытая ладонь двигается вбок и обратно. Это одиночная адаптация сцены рукопожатия: второго участника камера не требует. Сама картинка — из указанной мемной сцены.',image:'/media/dud.jpg',source:p('dud-i-shherbakov-pozhimayut-ruki'),year:'2023',pack:'special',emoji:'🤝',accent:'#ded9e5'},
 {id:'mouse',title:'Мыш кродеться',caption:'Тихо-тихо.',gesture:'paws',hint:'Собери две кисти лапками',detail:'Две согнутые кисти отдельно перед грудью. Условный жест к мему: перемещение мыши или крадущуюся походку камера не проверяет.',image:'/media/mouse.jpg',source:p('mysh-krodyotsya'),year:'2018',pack:'classic',emoji:'🐭',accent:'#e4dfd6'},
 {id:'natasha',title:'Наташ, мы всё уронили',caption:'Вообще всё. Честно.',gesture:'facepalm',hint:'Раскрытая ладонь на лоб',detail:'Поднеси открытую ладонь ко лбу. Это реакция на случившееся, а не буквальное повторение позы котов.',image:'/media/natasha.png',source:p('natash-my-tam-vsyo-uronili'),year:'2020',pack:'classic',emoji:'🙀',accent:'#e7decf'},
 {id:'ochki',title:'Очки ннада?',caption:'Есть предложение.',gesture:'glasses',hint:'Указательный палец к переносице',detail:'Коснись указательным пальцем переносицы, как будто поправляешь очки. Остальные пальцы согни. Предмет-очки не определяется.',image:'/media/ochki.jpg',source:p('ochki-nnada'),year:'Классика',pack:'classic',emoji:'👓',accent:'#dddce4'},
 {id:'kandibober',title:'Кандибобер',caption:'Это вам не просто так.',gesture:'point',hint:'Указательный палец вверх',detail:'Покажи указательный палец вверх, сбоку от лица. Это условный жест запуска, не определение головного убора или личности.',image:'/media/kandibober.jpg',source:p('kandibober'),year:'2010',pack:'classic',emoji:'🎩',accent:'#e6d4d7'},
 {id:'goodbye',title:'Давай, до свидания',caption:'Разговор окончен.',gesture:'wave',hint:'Помаши ладонью туда-обратно',detail:'Раскрой одну ладонь и махни ей вправо-влево. Жест совпадает по смыслу с прощанием; источник — азербайджанская мейхана, ставшая мемом Рунета.',image:'/media/goodbye.jpg',source:p('davaj-do-svidaniya'),year:'2012',pack:'classic',emoji:'👋',accent:'#e4dacb'},
 {id:'uninvited',title:'Я вас не звал!',caption:'Идите обратно.',gesture:'shrug',hint:'Две раскрытые ладони в стороны',detail:'Покажи две открытые ладони по сторонам ниже подбородка. Условный жест «вы кто такие», без распознавания предметов и помещения.',image:'/media/uninvited.png',source:p('vy-kto-takie-ya-vas-ne-zval'),year:'Классика',pack:'classic',emoji:'✋',accent:'#dadfce'},
 {id:'litvinkov',title:'Борщ с капусткой',caption:'Но не красный.',gesture:'pinch',hint:'Сведи большой и указательный пальцы',detail:'Сведи большой и указательный пальцы, остальные согни — словно показываешь щепотку приправы. Это ассоциация с едой, не исходная поза Никиты Литвинкова.',image:'/media/litvinkov.jpg',source:p('nikita-litvinkov'),year:'2008',pack:'classic',emoji:'🍲',accent:'#d9dfd3'},
 {id:'rybov',title:'Вы продоёте рыбов?',caption:'Красивое.',gesture:'fish',hint:'Разведи руки и открой рот',detail:'Покажи размер рыбы двумя разведёнными руками и открой рот. Это условный жест к диалогу котов с продавцом.',image:'/media/rybov.jpg',source:p('vy-prodaete-rybov'),year:'2021',pack:'classic',emoji:'🐠',accent:'#e0dbd3'},
 {id:'borisov',title:'Юра Борисов за столом',caption:'Невозмутимость — тоже талант.',gesture:'wait',hint:'Сложи кисти низко перед собой',detail:'Сложи обе кисти перед собой ниже груди и удерживай. Это адаптация посадки; само наличие стола и личность человека не определяются.',image:'/media/borisov-real.jpg',source:p('yura-borisov-za-stolom'),year:'2025',pack:'fresh',emoji:'🗿',accent:'#ded9d2'},
 {id:'know',title:'Знаю, но не могу доказать',caption:'Доказательства будут. Наверное.',gesture:'squint',hint:'Прищурь оба глаза',detail:'Убери кисти из кадра и прищурь оба глаза, не закрывая их полностью. Рот расслаблен, без широкой улыбки. Удержи прищур полсекунды. Кулак у подбородка больше не запускает этот мем.',image:'/media/know.jpg',source:p('znayu-no-ne-mogu-dokazat'),year:'2025',pack:'fresh',emoji:'🧐',accent:'#d9d8d5'},
];
