import type {Meme} from './catalog';
export const legends:Meme[]=[
 {id:'nichosi',title:'Ничоси!',caption:'Масштаб неожиданности.',gesture:'shockHands',hint:'Обе ладони над головой + открытый рот',detail:'Подними обе раскрытые ладони выше головы и открой рот. Без открытого рта это «Превед». Удержи позу четверть секунды.',image:'/media/nichosi.jpg',source:'https://memepedia.ru/kartinki-nichosi/',year:'2015',pack:'classic',emoji:'😲',accent:'#e2e5dc'},
 {id:'dratuti',title:'Дратути',caption:'А вот и я.',gesture:'peekHello',hint:'Высунь голову сбоку кадра с поднятой ладонью',detail:'Начни в центре. Смести лицо к левому или правому краю кадра и верни к центру с одной раскрытой ладонью. После появления помаши рукой. Нужен именно вход сбоку, а не постоянная ладонь у плеча.',image:'/media/dratuti.jpg',source:'https://memepedia.ru/chto-znachit-dratuti/',year:'2016',pack:'classic',emoji:'👋',accent:'#e9dfca'},
 {id:'norma',title:'Это норма',caption:'Спокойно. Это норма.',gesture:'nod',hint:'Один отчётливый кивок вниз и обратно',detail:'Посмотри прямо, не улыбайся широко. Опусти подбородок и верни голову обратно, не двигая корпусом. Руки опусти. Это условный жест одобрения, не медицинское заключение.',image:'/media/norma.jpg',source:'https://memepedia.ru/elena-malysheva-eto-norma/',year:'2013',pack:'classic',emoji:'😌',accent:'#dbe5ce'},
 {id:'nenado',title:'Можно ненадо',caption:'Давайте без этого.',gesture:'headNo',hint:'Покачай головой влево-вправо с просительной гримасой',detail:'Подними внутренние края бровей, опусти уголки губ и покачай головой из стороны в сторону. Руки опусти. Грустная гримаса без движения тоже может вызвать эту реакцию.',image:'/media/nenado.jpg',source:'https://memepedia.ru/mozhno-nenado/',year:'2018',pack:'classic',emoji:'🥺',accent:'#ecdfc9'},
 {id:'no-money',title:'Денег нет, но вы держитесь',caption:'Бюджет согласован.',gesture:'shrug',hint:'Разведи раскрытые ладони ниже подбородка',detail:'Покажи две открытые ладони по сторонам ниже подбородка и замри. Руки должны быть полностью видны. Это условный жест пустых рук, речь не распознаётся.',image:'/media/no-money.jpg',source:'https://memepedia.ru/deneg-net-no-vy-derzhites/',year:'2016',pack:'classic',emoji:'💸',accent:'#e5e0d7'},
];
export const coreIds=['tinkov-tongue','tinkov-ok','tinkov-wow','oxxy-think','fish','paws','fail','okak','wait','squirrel-goodbye','nichosi','dratuti','norma','nenado','no-money','cook'];
export const callIds=coreIds.filter(id=>!['fish','tinkov-tongue'].includes(id));
