import {migrateRouteKey} from './routeMigration';
import type {Meme} from './catalog';
import {expressionBindings,recognitionRoutes} from './expressions';
import type {ExpressionAssignments} from './preferences';
export const routeKey=(m:Pick<Meme,'id'|'gesture'>)=>`${m.id}:${m.gesture}`;
export const routeHint=(m:Meme)=>expressionBindings.find(b=>b.gesture===m.gesture)?.hint??m.hint;
export function selectedRoutes(memes:Meme[],assignments:ExpressionAssignments,keys:string[]|null){return memes.flatMap(m=>recognitionRoutes(m,assignments)).filter(m=>keys===null||keys.map(migrateRouteKey).includes(routeKey(m)));}
export function toggleRoute(keys:string[],route:Meme,on:boolean){const remaining=keys.filter(k=>on?!k.endsWith(`:${route.gesture}`):k!==routeKey(route));return on?[...remaining,routeKey(route)]:remaining;}
export function guideMarkdown(memes:Meme[],assignments:ExpressionAssignments={},keys:string[]|null=null){
 const rows=memes.map((m,i)=>{const routes=recognitionRoutes(m,assignments);const actions=routes.map(r=>`${routeHint(r)}${keys===null?'':keys.includes(routeKey(r))?' [включено]':' [выключено]'}`).join('; ')||'Нет назначенного выражения — выбери его во вкладке «Эмоции»';const shared=routes.map(r=>({r,others:memes.filter(n=>n.id!==m.id&&recognitionRoutes(n,assignments).some(x=>x.gesture===r.gesture))})).filter(x=>x.others.length).map(x=>`${routeHint(x.r)}: ${x.others.map(n=>n.title).join(', ')}`).join('; ');return `| ${i+1} | ${m.title} | ${actions} | ${m.video?'Видео':m.image.endsWith('.gif')?'GIF':'Картинка'}${m.audio?' + звук':''} | ${shared||'—'} |`;});
 return '# Все 48 мемов и условия запуска\n\nЭто справочник фактических маршрутов приложения, а не обещание распознавания персонажа или точной позы оригинала. Настраиваемая мимика требует убрать кисти из кадра. Жесты требуют видимого лица и кистей. Перед проверкой — нейтральная калибровка. Короткие мимические реакции удерживаются минимум 0,45 с, ручные — по настройке (обычно 0,25 с); для повторения верни нейтральную позу.\n\nВ точном наборе для одного действия выбирается один мем; его альтернативные действия включаются отдельными галочками. При выключенном точном наборе остаётся старый выбор паков.\n\n| № | Мем | Что сделать | Материал | Другие мемы с тем же действием |\n|---|---|---|---|---|\n'+rows.join('\n')+'\n\n## Подробные условия\n\n'+memes.map(m=>`### ${m.title}\n\n${m.detail}\n\nИсточник: ${m.source}\n`).join('\n')+'\n## Ограничения\n\nЯзык, папка, рыба, очки, кот, речь и личность человека не распознаются отдельно. Некоторые жесты — условные кнопки для мема, что указано в условиях карточки. Полное закрытие лица или кисти может прекратить распознавание. Белка воспроизводится минимум 7 секунд, чтобы успеть исчезнуть. Видео/звук в списке — доступные материалы; звук в микрофон звонка не маршрутизируется. Пороги на разных людях требуют живой проверки.\n';
}
